### ISSUE TITLE
support for private sub reddits

### ISSUE THREAD

**Issue by rasjani** [rasjani/plugin.video.reddit_tv#1]
- [x] investigate reddit api's what would it take to support login 
- [ ] mvp implementation to add private sub reddits 
- [ ] consider populating populating local sub-reddit list from account's subscribed subs .

**Comment by heio123** [comment]
Hey any update on the private sub issue?

**Comment by rasjani** [comment]
Only update so far is that i now have a better clue what it would take to support private subs. 

The thing is, the current set of calls to reddit from the addon are not that suited for sessions that require a login and im too lazy to start fixing all that should be fixed. Another option is that i'll rewrite the network code to use https://github.com/praw-dev/praw - which should be very doable.

**Comment by rasjani** [comment]
Praw is a no go and reddit api does not provide login without oauth (which is slightly problematic with or without praw) ..

**Comment by rasjani** [comment]
Not going to implement these ..
