### ISSUE TITLE
support for comments on android tv

### ISSUE THREAD

**Issue by ghost** [rasjani/plugin.video.reddit_tv#2]
hi could you please support opening comments with sync for reddit android app when using kodi on android or just m.reddit.com and chrome?
thanks

**Comment by rasjani** [comment]
I have no access to any android devices, so i can't really test how this would work.  

Patches welcome

**Comment by rasjani** [comment]
trying to get proper android support implemented for plugin.program.chrome.launcher  - when i get that done - i probably have a proper way to implement this .. stay tuned ..

**Comment by ghost** [comment]
thanks!

**Comment by rasjani** [comment]
updated plugin.program.chrome.launcher has now been requested to be integrated  to official repos ..  If you feel adventurous, you can grap the v1.2.0 zip from here: https://github.com/rasjani/plugin.program.chrome.launcher/releases and master branch zip of this repo and try it out .. or wait before official release..

I tried on android tablet and it seemed to work..

**Comment by rasjani** [comment]
the chrome launcher plugin wont be landing to official repo's - atleast with my changes so i'm closing this for now ..
