### ISSUE TITLE
How can I get my saved videos from reddit to show up in reddit viewer 

### ISSUE THREAD

**Issue by zsquared24** [rasjani/plugin.video.reddit_tv#8]
How can I get the videos I save from the documentary sub to show up on the viewer/ I know I can watch them on documentaries but I want just the ones I save.  Can I do just those from my account which I saved

**Comment by rasjani** [comment]
add the folder where you save as source or use browser. Also, saving content has been removed  from most parts of this addon so either you are using outdated version or a fork.

**Comment by zsquared24** [comment]
That is not what I meant.  I dont want to save stuff on the addon.  I want
to use the stuff I have saved on my regular reddit account as a playlist.
For example I go to documentaries on my browser firefox.  I save the ones I
like from reddit to the saved section of my profile.
reddit.com/user/yourname/saved/

**Comment by rasjani** [comment]
Aah, it sounded like you where trying to save the clips directly to your local storage .. 

Ok, currently that is not possible but that sounds like a decent idea.. i'll look into this..

**Comment by rasjani** [comment]
checked .. https://www.reddit.com/user/XXX/saved.json - requires authentication.

Wont implement..

**Comment by zsquared24** [comment]
Thanks for the help, I understand why it wont work now.  There is no way to
log it into my reddit account.  I think it would be a great idea for an
addon though since it is so much easier to save what you like into a list
in your saved section of profile.  Maybe someday

**Comment by rasjani** [comment]
Yeah.  It's not that I don't like the idea - I have evaluated praw (python Reddit API) and I don't personally want to implement oauth authentication with it because it would require too much work.  For bacontv (my in progress rewrite) - I might reconsider but for this addon, nah - too much work.

**Comment by rasjani** [comment]
Ask the guy who who maintains a fork - he might be interested to implement this.

**Comment by zsquared24** [comment]
Don't know what a fork is I dont have that addon.  I am kinda new to kodi
just always used online streaming sites until recently I didn't know what I
was missing.  It is a good idea seems to me anyways.  Wish I had the skill
to do it myself but wouldnt know where to start.  lol Have a great one
